cp Dockerfile.forReactFrontEnd AccountFront/Dockerfile
cp Dockerfile.forSpringbootBackEnd RealAccountApi/Dockerfile
cp Dockerfile.forSpringbootBackEnd RealAccountNumGenApi/Dockerfile
cp Dockerfile.forSpringbootBackEnd RealAccountPrizeApi/Dockerfile
cp Dockerfile.forSpringbootBackEnd RealAccountConsumer/Dockerfile
